### ISSUE TITLE
Banner disappearing issue 

### ISSUE THREAD

**Issue by RavindraEnakollu** [bschlintz/spfx-message-banner#10]
We have deployed the GitHub Banner solution without any issue and we are able to see the banner when we open the site but it is getting disappear after few seconds.

Could you please confirm which ClientSideComponentId we have to use in pnp powershell while configuration.
We have used the same as given in example. Is that correct id?
ClientSideComponentId "1e2688c4-99d8-4897-8871-a9c151ccfc87"

Please help us in resolving automatic disappearing of banner notification.

**Comment by bschlintz** [comment]
Hi @RavindraEnakollu, that should be the correct ID.

For troubleshooting, I would suggest reviewing the F12 Developer console on a site with the issue to see if there are any errors. Since it does render and then disappears, it could be throwing an exception or there is a conflict with another SPFx solution on the same site or deployed tenant-wide. You could try configuring the banner on a new standalone site to see if it has the same issue. Beyond that, I would check to see what other solutions are deployed to make sure there aren't any conflicts such as another solution with the same ID or the same solution deployed at multiple scopes (e.g. site and tenant).
